name: Auto Create Pull Request

on:
  push:
    branches-ignore:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Get last commit message and author
        id: last-commit
        run: |
          echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "commit_author=$(git log -1 --pretty=%an)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"  # or master
          source_branch: "${{ github.ref }}"
          pr_title: "${{ env.commit_author }}: ${{ env.commit_message }}"
          pr_body: "This is an automated pull request to merge changes from the new branch to the develop branch."
          github_token: ${{ secrets.GITHUB_TOKEN }}
